language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    global:
        - COMPOSER_FLAGS='--prefer-stable'

matrix:
    include:
        - php: 5.3.3
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 5.6
          env: COMPOSER_FLAGS='' # Run against the latest dev versions

before_install: composer self-update # remove this once the Travis upgrade of February 2015 is deployed

install: composer update $COMPOSER_FLAGS

script: phpunit -v
